### ISSUE TITLE
Automatically sign up to services

### ISSUE THREAD

**Issue by Jnesselr** [Denhac/ApplicationAPI#13]
I would like the new member to be invited to slack and the email list on signup.

There is an undocumented API to add a member to slack, because it's still not an "official" endpoint: https://github.com/ErikKalkoken/slackApiDoc/blob/master/users.admin.invite.md

**Comment by stonaker** [comment]
Here is the link I had saved to rtfm to research later; it is the g-Suite API docs for user management: https://developers.google.com/admin-sdk/directory/v1/guides/manage-users

**Comment by Jnesselr** [comment]
This now works with the new system as part of the denhac/denhac-webhooks project.
